[project]
name = "demo-magician-python-64-master"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.7"
dependencies = []

[tool.uv.workspace]
members = [
    "1211dobotteaching",
]
